import {
  analyze,
  createLogger,
  createRegistry,
  defineRule,
  generatedMarker,
  memoryFileSystem,
  memorySink,
  parseConfig,
} from '@flowpact/core';
import { describe, expect, it } from 'vitest';
import { byCode, codes, lint, WF, yaml } from './helpers';

describe('generatedMarker', () => {
  it.each([
    [
      '# This file was automatically generated by gh-aw (v0.87.10). DO NOT EDIT.\nname: x\n',
      'automatically generated',
    ],
    ['# AUTOGENERATED FILE - DO NOT EDIT MANUALLY\nname: x\n', 'AUTOGENERATED'],
    ['# Owner(s): ["oncall: releng"]\n# @generated DO NOT EDIT MANUALLY\n\nname: x\n', '@generated'],
    ['# generated by praktika\n\nname: x\n', 'generated'],
    ['# This workflow was generated from ci.yml.j2\nname: x\n', 'This workflow was generated'],
    ['---\n# Code generated by gen-ci. DO NOT EDIT.\nname: x\n', 'DO NOT EDIT'],
    // gh-aw puts long metadata lines first.
    [
      '# gh-aw-metadata: {"a":1}\n# gh-aw-manifest: {"b":2}\n# This file was automatically generated by gh-aw. DO NOT EDIT.\non: push\n',
      'automatically generated',
    ],
    ['﻿# auto-generated from ci.yml.j2\r\non: push\r\n', 'auto-generated'],
  ])('finds the marker in %j', (text, marker) => {
    expect(generatedMarker(`${WF}/w.yml`, text)).toBe(marker);
  });

  it.each([
    ['name: x\n# DO NOT EDIT the job names, they are required checks\non: push\n'],
    ['# Owner(s): x\nname: linux-binary-test\n\n# /run.sh is generated by binary_linux_test.sh\non: push\n'],
    [
      '# The real workflow is generated by praktika from ci/workflows/x.py, which replaces this file.\nname: x\n',
    ],
    [`${'# license\n'.repeat(10)}# DO NOT EDIT\nname: x\n`],
    ['on: push\n'],
  ])('ignores %j', (text) => {
    expect(generatedMarker(`${WF}/w.yml`, text)).toBeUndefined();
  });

  it('recognizes GitHub Agentic Workflows lock files by name, and generated actions', () => {
    expect(generatedMarker(`${WF}/triage.lock.yml`, 'on: push\n')).toBe('.lock.yml');
    expect(generatedMarker('.github/actions/x/action.yml', '# DO NOT EDIT\nruns: {}\n')).toBe('DO NOT EDIT');
  });
});

/**
 * A reusable workflow with dead declarations (FP104, FP203, FP303), `secrets: inherit` (FP204) and an output its
 * github-script never writes (FP304); it calls a hand-written workflow without a required input (FP101) and is called
 * with an unknown input (FP102).
 */
const project = (path: string, header = '') => ({
  [path]: `${header}on:
  workflow_call:
    inputs:
      unused: { type: string }
      mode: { type: string, required: true }
    secrets:
      NEVER_READ: {}
jobs:
  agent:
    runs-on: x
    outputs:
      dead: \${{ steps.s.outputs.result }}
    steps:
      - id: s
        uses: actions/github-script@v8
        with:
          script: core.setOutput('a', 1)
      - run: echo \${{ steps.s.outputs.b }} \${{ inputs.mode }}
  helper:
    uses: ./.github/workflows/_shared.yml
    secrets: inherit
`,
  [`${WF}/_shared.yml`]: yaml`
    on:
      workflow_call:
        inputs:
          required-input: { type: string, required: true }
    jobs:
      j:
        runs-on: x
        steps:
          - run: echo \${{ inputs.required-input }}
  `,
  [`${WF}/caller.yml`]: yaml`
    on: push
    jobs:
      call:
        uses: ./${path}
        with:
          mode: x
          bogus: y
  `,
});

describe('generated files', () => {
  it('reports everything in a hand-written file', () => {
    const r = lint(project(`${WF}/agent.yml`, '# Maintained by the platform team\n'));
    expect(codes(r).sort()).toEqual(['FP101', 'FP102', 'FP104', 'FP203', 'FP204', 'FP303', 'FP304']);
  });

  it.each([
    ['a gh-aw lock file', `${WF}/agent.lock.yml`, ''],
    ['a DO NOT EDIT header', `${WF}/agent.yml`, '# Code generated by gen-ci. DO NOT EDIT.\n'],
  ])('skips findings about the internals of %s but checks its calls', (_label, path, header) => {
    const r = lint(project(path, header));
    // The call from the generated file into a hand-written workflow, and the call into the generated file.
    expect(codes(r).sort()).toEqual(['FP101', 'FP102']);
    expect(byCode(r, 'FP101')[0]?.loc.file).toBe(path);
    expect(byCode(r, 'FP102')[0]?.loc.file).toBe(`${WF}/caller.yml`);
    expect(
      r.logs.some((l) => l.message === 'skipped 5 finding(s) about the internals of 1 generated file(s)'),
    ).toBe(true);
  });

  it('keeps generated files in the graph', () => {
    const r = lint(project(`${WF}/agent.lock.yml`));
    expect(r.project.workflows.get(`${WF}/agent.lock.yml`)?.generated).toBe('.lock.yml');
    expect(r.project.workflows.get(`${WF}/caller.yml`)?.generated).toBeUndefined();
    expect(r.index.usagesOf(`${WF}/agent.lock.yml#inputs.mode`)).toHaveLength(1);
  });

  it('lets plugin rules opt in with generatedFiles: skip', () => {
    const rule = (generatedFiles?: 'skip' | 'report') =>
      defineRule({
        code: 'ACME701',
        name: 'acme-everywhere',
        category: 'hygiene',
        defaultSeverity: 'warning',
        docsUrl: 'https://example.com/acme701',
        docs: { summary: 's', why: 'w', fix: 'f' },
        ...(generatedFiles ? { generatedFiles } : {}),
        check(ctx) {
          for (const wf of ctx.index.project.workflows.values())
            ctx.report({ message: 'x', loc: wf.source.loc(0, 0), symbol: wf.path });
        },
      });
    const files = (generatedFiles?: 'skip' | 'report') =>
      analyze({
        root: '/virtual/repo',
        fs: memoryFileSystem(project(`${WF}/agent.lock.yml`)),
        config: parseConfig({}),
        validateSchema: false,
        registry: createRegistry().register(rule(generatedFiles)),
        logger: createLogger({ level: 'error', sink: memorySink() }),
        only: ['ACME701'],
      }).findings.map((f) => f.loc.file);
    expect(files()).toContain(`${WF}/agent.lock.yml`);
    expect(files('report')).toContain(`${WF}/agent.lock.yml`);
    expect(files('skip')).toEqual([`${WF}/_shared.yml`, `${WF}/caller.yml`]);
  });
});
