/** wfc → flowpact (0.2.0): the old file locations keep working, old rule codes point at the new ones, and migrate moves files. */
import { existsSync, mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import {
  analyze,
  applyMigration,
  CONTRACT_HEADER,
  ConfigError,
  createRegistry,
  defineRule,
  loadConfig,
  memoryFileSystem,
  parseConfig,
  planContracts,
  planMigration,
} from '@flowpact/core';
import { describe, expect, it } from 'vitest';
import { codes, WF } from './helpers';

const OLD = '.github/workflow-contracts';
const workflow = 'on: workflow_call\njobs:\n  j:\n    runs-on: x\n    steps: [{ run: x }]\n';
const oldHeader =
  '# Generated by wfc — do not edit by hand. Run `wfc generate` to update.\n# Docs: https://rumankazi.github.io/wfc/docs/contracts\n';

/** Exactly what wfc 0.1.x wrote: flowpact's contract with the old header and `$schema` URL. */
const asWfc = (text: string) =>
  text
    .replace(CONTRACT_HEADER, oldHeader)
    .replace('https://rumankazi.github.io/flowpact/schemas/', 'https://rumankazi.github.io/wfc/schemas/');

function lockedLegacy(files: Record<string, string>, transform = asWfc): Record<string, string> {
  const fresh = planContracts(
    analyze({ root: '/v', fs: memoryFileSystem(files), validateSchema: false, only: [], repository: 'a/b' })
      .index,
    memoryFileSystem(files),
  );
  const out = { ...files };
  for (const e of fresh.entries) out[e.file.replace('.github/flowpact/contracts', OLD)] = transform(e.after!);
  return out;
}

const check = (files: Record<string, string>) =>
  analyze({
    root: '/v',
    fs: memoryFileSystem(files),
    validateSchema: false,
    checkContracts: true,
    repository: 'a/b',
  });

function repo(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), 'flowpact-rename-'));
  for (const [file, text] of Object.entries(files)) {
    mkdirSync(dirname(join(root, file)), { recursive: true });
    writeFileSync(join(root, file), text);
  }
  return root;
}

describe('pre-0.2.0 locations', () => {
  it('reads the old config and reports FP904', () => {
    const root = repo({
      [`${WF}/ci.yml`]: workflow,
      [`${OLD}/wfc.config.yml`]: 'rules:\n  unused-input: off\n',
    });
    const loaded = loadConfig(root);
    expect(loaded.file).toBe(`${OLD}/wfc.config.yml`);
    expect(loaded.legacy).toBe(true);
    const r = analyze({ root, config: loaded.config, configFile: loaded.file, repository: 'a/b' });
    expect(codes(r)).toContain('FP904');
  });

  it('prefers the new config when both exist', () => {
    const root = repo({
      [`${OLD}/wfc.config.yml`]: 'rules: {}\n',
      '.github/flowpact/flowpact.config.yml': 'rules: {}\n',
    });
    expect(loadConfig(root).file).toBe('.github/flowpact/flowpact.config.yml');
    expect(loadConfig(root).legacy).toBeUndefined();
  });

  it('keeps using contracts written by wfc 0.1.x, unchanged, until they are migrated', () => {
    const locked = lockedLegacy({ [`${WF}/r.yml`]: workflow });
    expect(locked[`${OLD}/workflows/r.contract.yml`]).toContain('# Generated by wfc');
    const r = check(locked);
    expect(r.contracts?.legacyDir).toBe(true);
    expect(r.contracts?.entries.map((e) => [e.file, e.status])).toEqual([
      [`${OLD}/workflows/r.contract.yml`, 'unchanged'],
    ]);
    expect(codes(r).filter((c) => c.startsWith('FP8'))).toEqual([]);
    expect(codes(r)).toContain('FP904');
  });

  it('accepts CRLF contracts written by wfc', () => {
    const r = check(lockedLegacy({ [`${WF}/r.yml`]: workflow }, (t) => asWfc(t).replace(/\n/g, '\r\n')));
    expect(codes(r).filter((c) => c.startsWith('FP8'))).toEqual([]);
  });

  it('still compares old contracts in a half-migrated repository', () => {
    const files = { [`${WF}/a.yml`]: workflow, [`${WF}/b.yml`]: workflow };
    const locked = lockedLegacy(files);
    // a.yml was migrated, b.yml was not; b's workflow then gains a required input.
    const mixed: Record<string, string> = {
      ...locked,
      '.github/flowpact/contracts/workflows/a.contract.yml': locked[`${OLD}/workflows/a.contract.yml`]!,
      [`${WF}/b.yml`]:
        'on:\n  workflow_call:\n    inputs:\n      x: { required: true }\njobs:\n  j:\n    runs-on: x\n    steps: [{ run: x }]\n',
    };
    delete mixed[`${OLD}/workflows/a.contract.yml`];
    const r = check(mixed);
    expect(codes(r)).toContain('FP803');
    expect(codes(r)).not.toContain('FP801');
    expect(codes(r)).toContain('FP904');
  });
});

describe('renamed rule codes', () => {
  it('suggests the FP code for an old WFC code, without accepting it', () => {
    const run = (config: Record<string, unknown>) =>
      analyze({
        root: '/v',
        fs: memoryFileSystem({ [`${WF}/a.yml`]: workflow }),
        validateSchema: false,
        config: parseConfig(config),
        repository: 'a/b',
      });
    try {
      run({ rules: { WFC104: 'off' } });
      expect.unreachable();
    } catch (err) {
      expect(err).toBeInstanceOf(ConfigError);
      expect((err as ConfigError).issues[0]).toMatch(
        /did you mean FP104\? — rule codes were renamed from WFC to FP/,
      );
    }
  });

  it('keeps WFC reserved for plugins', () => {
    const plugin = defineRule({
      code: 'WFC701',
      name: 'acme-thing',
      category: 'other' as never,
      defaultSeverity: 'warning',
      docs: { summary: 'x'.repeat(30), why: 'y'.repeat(40), fix: 'z'.repeat(20) },
      docsUrl: 'https://example.com',
      check() {},
    });
    expect(() => createRegistry().register(plugin)).toThrow(/the WFC prefix is reserved/);
  });
});

describe('flowpact migrate', () => {
  it('moves the config and contracts, renames codes and rewrites URLs and headers', () => {
    const root = repo({
      [`${OLD}/wfc.config.yml`]:
        '# yaml-language-server: $schema=https://rumankazi.github.io/wfc/schemas/config/v1.json\nrules:\n  WFC104: off\noverrides:\n  - rule: WFC101\n    file: x\n    reason: kept for the migration\n',
      [`${OLD}/workflows/r.contract.yml`]: `${oldHeader}$schema: https://rumankazi.github.io/wfc/schemas/contract/v1.json\nversion: 1\n`,
      [`${OLD}/notes.md`]: 'keep me\n',
    });
    const plan = planMigration(root);
    expect(plan.moves.map((m) => [m.from, m.to])).toEqual([
      [`${OLD}/wfc.config.yml`, '.github/flowpact/flowpact.config.yml'],
      [`${OLD}/workflows/r.contract.yml`, '.github/flowpact/contracts/workflows/r.contract.yml'],
    ]);
    expect(plan.leftovers).toEqual([
      { file: `${OLD}/notes.md`, reason: 'is not a flowpact file and stays where it is' },
    ]);
    applyMigration(root, plan);
    const config = readFileSync(join(root, '.github/flowpact/flowpact.config.yml'), 'utf8');
    expect(config).toContain('FP104: off');
    expect(config).toContain('rule: FP101');
    expect(config).toContain('rumankazi.github.io/flowpact/schemas/config/v1.json');
    const contract = readFileSync(join(root, '.github/flowpact/contracts/workflows/r.contract.yml'), 'utf8');
    expect(contract.startsWith(CONTRACT_HEADER)).toBe(true);
    expect(contract).toContain('rumankazi.github.io/flowpact/schemas/contract/v1.json');
    expect(existsSync(join(root, `${OLD}/wfc.config.yml`))).toBe(false);
    expect(existsSync(join(root, `${OLD}/workflows`))).toBe(false);
    expect(existsSync(join(root, `${OLD}/notes.md`))).toBe(true);
  });

  it('refuses to overwrite existing files', () => {
    const root = repo({
      [`${OLD}/wfc.config.yml`]: 'rules: {}\n',
      '.github/flowpact/flowpact.config.yml': 'rules: {}\n',
    });
    const plan = planMigration(root);
    expect(plan.conflicts).toEqual(['.github/flowpact/flowpact.config.yml']);
    expect(() => applyMigration(root, plan)).toThrow(/Already exists/);
    expect(existsSync(join(root, `${OLD}/wfc.config.yml`))).toBe(true);
  });

  it('handles CRLF headers, lowercase codes, and leaves other wfc URLs alone', () => {
    const root = repo({
      [`${OLD}/wfc.config.yml`]: 'rules:\n  wfc104: off\n',
      [`${OLD}/workflows/r.contract.yml`]:
        `${oldHeader}$schema: https://rumankazi.github.io/wfc/schemas/contract/v1.json\ndescription: see https://rumankazi.github.io/wfc/docs/cli\n`.replace(
          /\n/g,
          '\r\n',
        ),
    });
    applyMigration(root, planMigration(root));
    expect(readFileSync(join(root, '.github/flowpact/flowpact.config.yml'), 'utf8')).toContain('FP104: off');
    const contract = readFileSync(join(root, '.github/flowpact/contracts/workflows/r.contract.yml'), 'utf8');
    expect(contract.startsWith(CONTRACT_HEADER)).toBe(true);
    expect(contract).toContain('$schema: https://rumankazi.github.io/flowpact/schemas/contract/v1.json');
    expect(contract).toContain('description: see https://rumankazi.github.io/wfc/docs/cli');
  });

  it('lists symlinks instead of moving them, and refuses a symlinked directory', () => {
    const root = repo({ 'shared/wfc.config.yml': 'rules: {}\n', [`${OLD}/workflows/r.contract.yml`]: 'x\n' });
    symlinkSync('../../shared/wfc.config.yml', join(root, `${OLD}/wfc.config.yml`));
    const plan = planMigration(root);
    expect(plan.leftovers).toEqual([
      { file: `${OLD}/wfc.config.yml`, reason: 'is a symlink; move it by hand' },
    ]);
    const other = repo({ 'ci/contracts/workflows/r.contract.yml': 'x\n' });
    mkdirSync(join(other, '.github'), { recursive: true });
    symlinkSync('../ci/contracts', join(other, OLD));
    expect(() => planMigration(other)).toThrow(/is a symlink/);
  });

  it('has nothing to do in a migrated repository', () => {
    expect(planMigration(repo({ '.github/flowpact/flowpact.config.yml': 'rules: {}\n' })).moves).toEqual([]);
  });
});
