import { existsSync, lstatSync, mkdirSync, realpathSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { formatPatch, structuredPatch } from 'diff';
import { parse as parseYaml, stringify } from 'yaml';
import { z } from 'zod';
import { CONFIG_DIR } from './config';
import type { Json } from './expressions';
import { type ProjectIndex, sym } from './graph';
import type { ActionDecl, Binding, InputDecl, UnitDecl, WorkflowDecl } from './ir';
import { expandMatrix } from './matrix';
import { type FileSystem, insideRepository } from './project';
import { SCHEMA_VERSIONS, schemaUrl } from './version';

/** Where generated contracts live, relative to the repository root. */
export const CONTRACTS_DIR = `${CONFIG_DIR}/contracts`;

/** A contract as flowpact writes it: checkouts with core.autocrlf turn LF into CRLF. */
export function normalizeContractText(text: string): string {
  return text.replace(/\r\n/g, '\n');
}
export const CONTRACT_HEADER =
  '# Generated by flowpact — do not edit by hand. Run `flowpact generate` to update.\n# Docs: https://rumankazi.github.io/flowpact/docs/contracts\n';

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

const contractInputSchema = z
  .object({
    type: z.string().optional(),
    required: z.boolean(),
    default: z.json().optional(),
    description: z.string().optional(),
    options: z.array(z.string()).optional(),
  })
  .strict();

const contractCallSchema = z
  .object({
    job: z.string(),
    uses: z.string(),
    with: z.record(z.string(), z.string()).optional(),
    secrets: z.union([z.literal('inherit'), z.record(z.string(), z.string())]).optional(),
    needs: z.array(z.string()).optional(),
    matrix: z
      .object({ combinations: z.number().int(), keys: z.array(z.string()), exact: z.boolean() })
      .strict()
      .optional(),
  })
  .strict();

const contractUseSchema = z
  .object({
    job: z.string().optional(),
    step: z.string(),
    uses: z.string(),
    with: z.record(z.string(), z.string()).optional(),
  })
  .strict();

const contractConsumerSchema = z
  .object({
    from: z.string(),
    job: z.string().optional(),
    step: z.string().optional(),
    passes: z.array(z.string()),
    reads: z.array(z.string()),
  })
  .strict();

export const contractSchema = z
  .object({
    $schema: z.string(),
    version: z.literal(SCHEMA_VERSIONS.contract),
    kind: z.enum(['workflow', 'action']),
    path: z.string(),
    name: z.string().optional(),
    triggers: z.array(z.string()).optional(),
    interface: z
      .object({
        /** `workflow_call` inputs for workflows, `inputs` for actions. */
        inputs: z.record(z.string(), contractInputSchema),
        /** `workflow_dispatch` inputs (workflows only). */
        dispatchInputs: z.record(z.string(), contractInputSchema).optional(),
        secrets: z.record(z.string(), z.object({ required: z.boolean() }).strict()).optional(),
        outputs: z.record(
          z.string(),
          z.object({ description: z.string().optional(), value: z.string().optional() }).strict(),
        ),
      })
      .strict(),
    calls: z.array(contractCallSchema).optional(),
    uses: z.array(contractUseSchema).optional(),
    consumers: z.array(contractConsumerSchema),
  })
  .strict();

export type Contract = z.infer<typeof contractSchema>;
export type ContractInput = z.infer<typeof contractInputSchema>;

export function contractJsonSchema(): Record<string, unknown> {
  return { $id: schemaUrl('contract'), title: 'flowpact contract', ...z.toJSONSchema(contractSchema) };
}

// ---------------------------------------------------------------------------
// Building contracts from the graph
// ---------------------------------------------------------------------------

/** Locale-independent ordering, so contracts are byte-identical on every machine. */
export const byCodePoint = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

const sortedRecord = <T>(rec: Record<string, T>): Record<string, T> =>
  Object.fromEntries(Object.entries(rec).sort(([a], [b]) => byCodePoint(a, b)));

const bindingText = (b: Binding): string =>
  b.site ? b.site.text : typeof b.value === 'string' ? b.value : JSON.stringify(b.value);

function inputContract(i: InputDecl): ContractInput {
  return {
    ...(i.type ? { type: i.type } : {}),
    required: i.required,
    ...(i.hasDefault ? { default: i.default as Json } : {}),
    ...(i.description ? { description: i.description } : {}),
    ...(i.options ? { options: i.options } : {}),
  };
}

const stepRef = (s: { id?: string; index: number }) => s.id ?? `#${s.index + 1}`;

function workflowInterface(wf: WorkflowDecl): Contract['interface'] {
  const inputs: Record<string, ContractInput> = {};
  for (const i of Object.values(wf.call?.inputs ?? {})) inputs[i.name] = inputContract(i);
  const dispatchInputs: Record<string, ContractInput> = {};
  for (const i of Object.values(wf.dispatch?.inputs ?? {})) dispatchInputs[i.name] = inputContract(i);
  const secrets: Record<string, { required: boolean }> = {};
  for (const s of Object.values(wf.call?.secrets ?? {})) secrets[s.name] = { required: s.required };
  const outputs: Contract['interface']['outputs'] = {};
  for (const o of Object.values(wf.call?.outputs ?? {})) {
    outputs[o.name] = {
      ...(o.description ? { description: o.description } : {}),
      ...(o.value !== undefined
        ? { value: typeof o.value === 'string' ? o.value : JSON.stringify(o.value) }
        : {}),
    };
  }
  return {
    inputs: sortedRecord(inputs),
    ...(Object.keys(dispatchInputs).length ? { dispatchInputs: sortedRecord(dispatchInputs) } : {}),
    ...(Object.keys(secrets).length ? { secrets: sortedRecord(secrets) } : {}),
    outputs: sortedRecord(outputs),
  };
}

function actionInterface(a: ActionDecl): Contract['interface'] {
  const inputs: Record<string, ContractInput> = {};
  for (const i of Object.values(a.inputs)) inputs[i.name] = inputContract(i);
  const outputs: Contract['interface']['outputs'] = {};
  for (const o of Object.values(a.outputs)) {
    outputs[o.name] = {
      ...(o.description ? { description: o.description } : {}),
      ...(o.value !== undefined
        ? { value: typeof o.value === 'string' ? o.value : JSON.stringify(o.value) }
        : {}),
    };
  }
  return { inputs: sortedRecord(inputs), outputs: sortedRecord(outputs) };
}

function consumersOf(index: ProjectIndex, unit: UnitDecl): Contract['consumers'] {
  const out: Contract['consumers'] = [];
  if (unit.kind === 'workflow') {
    for (const c of index.callersOf(unit.path)) {
      const reads = Object.keys(unit.call?.outputs ?? {}).filter(
        (o) => index.usagesOf(sym.jobOutput(c.caller.path, c.job.id, o)).length > 0,
      );
      out.push({
        from: c.caller.path,
        job: c.job.id,
        passes: Object.keys(c.job.with).sort(),
        reads: reads.sort(),
      });
    }
  } else {
    for (const u of index.usersOf(unit.path)) {
      const reads = u.step.id
        ? Object.keys(unit.outputs).filter(
            (o) => index.usagesOf(sym.stepOutput(u.unit.path, u.job?.id, u.step.id!, o)).length > 0,
          )
        : [];
      out.push({
        from: u.unit.path,
        ...(u.job ? { job: u.job.id } : {}),
        step: stepRef(u.step),
        passes: Object.keys(u.step.with).sort(),
        reads: reads.sort(),
      });
    }
  }
  return out.sort((a, b) =>
    byCodePoint(`${a.from}#${a.job ?? ''}#${a.step ?? ''}`, `${b.from}#${b.job ?? ''}#${b.step ?? ''}`),
  );
}

function callsOf(wf: WorkflowDecl): Contract['calls'] {
  const calls: NonNullable<Contract['calls']> = [];
  for (const job of Object.values(wf.jobs)) {
    if (!job.uses) continue;
    const exp = job.matrix ? expandMatrix(job.matrix) : undefined;
    const withs = Object.fromEntries(Object.values(job.with).map((b) => [b.name, bindingText(b)]));
    const secrets = job.secretsInherit
      ? ('inherit' as const)
      : Object.fromEntries(Object.values(job.secrets).map((b) => [b.name, bindingText(b)]));
    calls.push({
      job: job.id,
      uses: job.uses.target ?? job.uses.raw,
      ...(Object.keys(withs).length ? { with: sortedRecord(withs) } : {}),
      ...(secrets === 'inherit' || Object.keys(secrets).length
        ? { secrets: secrets === 'inherit' ? secrets : sortedRecord(secrets) }
        : {}),
      ...(job.needs.length ? { needs: job.needs.map((n) => n.id).sort() } : {}),
      ...(exp && !exp.dynamic
        ? { matrix: { combinations: exp.combos.length, keys: [...exp.keys].sort(), exact: exp.exact } }
        : exp?.dynamic
          ? { matrix: { combinations: 0, keys: [], exact: false } }
          : {}),
    });
  }
  return calls.sort((a, b) => byCodePoint(a.job, b.job));
}

function usesOf(index: ProjectIndex, unit: UnitDecl): Contract['uses'] {
  const uses: NonNullable<Contract['uses']> = [];
  for (const u of index.actionUses.filter((x) => x.unit === unit)) {
    const withs = Object.fromEntries(Object.values(u.step.with).map((b) => [b.name, bindingText(b)]));
    uses.push({
      ...(u.job ? { job: u.job.id } : {}),
      step: stepRef(u.step),
      uses: u.action.path,
      ...(Object.keys(withs).length ? { with: sortedRecord(withs) } : {}),
    });
  }
  return uses.sort((a, b) => byCodePoint(`${a.job ?? ''}#${a.step}`, `${b.job ?? ''}#${b.step}`));
}

export function buildContract(index: ProjectIndex, unit: UnitDecl): Contract {
  const calls = unit.kind === 'workflow' ? callsOf(unit) : [];
  const uses = usesOf(index, unit);
  return {
    $schema: schemaUrl('contract'),
    version: SCHEMA_VERSIONS.contract,
    kind: unit.kind,
    path: unit.path,
    ...(unit.name ? { name: unit.name } : {}),
    ...(unit.kind === 'workflow' ? { triggers: [...unit.triggers].sort() } : {}),
    interface: unit.kind === 'workflow' ? workflowInterface(unit) : actionInterface(unit),
    ...(calls?.length ? { calls } : {}),
    ...(uses?.length ? { uses } : {}),
    consumers: consumersOf(index, unit),
  };
}

export function serializeContract(c: Contract): string {
  return `${CONTRACT_HEADER}${stringify(c, { lineWidth: 0, indent: 2, defaultStringType: 'PLAIN', singleQuote: true })}`;
}

/**
 * Repo-relative contract file for a unit:
 * `.github/workflows/ci.yml` → `.github/flowpact/contracts/workflows/ci.contract.yml`,
 * `.github/actions/setup` → `.github/flowpact/contracts/actions/setup.contract.yml`,
 * `tools/build` → `.github/flowpact/contracts/actions/tools__build.contract.yml`.
 */
export function contractFileFor(
  unit: Pick<UnitDecl, 'kind' | 'path'>,
  taken: Set<string> = new Set(),
  dir: string = CONTRACTS_DIR,
): string {
  const fileOf = (base: string) => `${dir}/${base}.contract.yml`;
  let base: string;
  if (unit.kind === 'workflow') {
    base = `workflows/${unit.path
      .split('/')
      .pop()!
      .replace(/\.ya?ml$/i, '')}`;
    if (taken.has(fileOf(base))) base = `workflows/${unit.path.split('/').pop()!}`;
  } else {
    const rel = unit.path.replace(/^\.github\/actions\//, '').replace(/^\.$/, 'root');
    base = `actions/${rel.split('/').join('__')}`;
  }
  // Paths that flatten to the same name (`tools/build` and `.github/actions/tools/build`) get a numeric suffix.
  const stem = base;
  for (let n = 2; taken.has(fileOf(base)); n++) base = `${stem}-${n}`;
  return fileOf(base);
}

// ---------------------------------------------------------------------------
// Semantic diff
// ---------------------------------------------------------------------------

export interface ContractChange {
  breaking: boolean;
  /** e.g. `inputs.config`, `outputs.url`, `calls.test.with.config`. */
  path: string;
  message: string;
}

const same = (a: unknown, b: unknown) => JSON.stringify(a) === JSON.stringify(b);

type AddChange = (breaking: boolean, path: string, message: string) => void;

function diffInputs(
  add: AddChange,
  key: 'inputs' | 'dispatchInputs',
  label: string,
  before: Record<string, ContractInput>,
  after: Record<string, ContractInput>,
  opts: { mustPass: (i: ContractInput) => boolean; additionsBreak: boolean },
): void {
  for (const [name, old] of Object.entries(before)) {
    const path = `${key}.${name}`;
    const cur = after[name];
    if (!cur) {
      add(true, path, `${label} "${name}" was removed — callers that pass it will fail`);
      continue;
    }
    if ((old.type ?? 'string') !== (cur.type ?? 'string')) {
      add(
        true,
        path,
        `${label} "${name}" changed type from ${old.type ?? 'string'} to ${cur.type ?? 'string'}`,
      );
    }
    const oldNeeds = opts.mustPass(old);
    const curNeeds = opts.mustPass(cur);
    if (!oldNeeds && curNeeds) add(true, path, `${label} "${name}" must now be passed by every caller`);
    else if (old.required !== cur.required) {
      add(false, path, `${label} "${name}" is now ${cur.required ? 'required' : 'optional'}`);
    }
    if (!same(old.default, cur.default)) {
      add(
        false,
        path,
        `${label} "${name}" default changed from ${JSON.stringify(old.default ?? null)} to ${JSON.stringify(cur.default ?? null)}`,
      );
    }
    if (!same(old.options, cur.options)) {
      const removed = (old.options ?? []).filter((o) => !(cur.options ?? []).includes(o));
      add(
        removed.length > 0,
        path,
        `${label} "${name}" options changed${removed.length ? ` (removed: ${removed.join(', ')})` : ''}`,
      );
    }
    if (old.description !== cur.description) add(false, path, `${label} "${name}" description changed`);
  }
  for (const [name, cur] of Object.entries(after)) {
    if (before[name]) continue;
    const needed = opts.mustPass(cur) && opts.additionsBreak;
    add(
      needed,
      `${key}.${name}`,
      `${label} "${name}" was added${needed ? ' and must be passed — existing callers do not pass it' : ''}`,
    );
  }
}

/** Classifies what changed between the locked contract and the current one. */
export function diffContracts(before: Contract, after: Contract): ContractChange[] {
  const changes: ContractChange[] = [];
  const add = (breaking: boolean, path: string, message: string) => changes.push({ breaking, path, message });
  const bi = before.interface;
  const ai = after.interface;

  const isWorkflow = before.kind === 'workflow';
  // Without `workflow_call` before, nobody could call the workflow: new call inputs/secrets break no caller.
  const wasCallable = !isWorkflow || (before.triggers ?? []).includes('workflow_call');
  diffInputs(add, 'inputs', isWorkflow ? 'input' : 'input', bi.inputs, ai.inputs, {
    // GitHub requires a `required` workflow_call input from every caller, even when it has a default.
    mustPass: (i) => (isWorkflow ? i.required : i.required && i.default === undefined),
    additionsBreak: wasCallable,
  });
  diffInputs(add, 'dispatchInputs', 'dispatch input', bi.dispatchInputs ?? {}, ai.dispatchInputs ?? {}, {
    mustPass: (i) => i.required && i.default === undefined,
    additionsBreak: true,
  });

  const bs = bi.secrets ?? {};
  const as = ai.secrets ?? {};
  for (const [name, old] of Object.entries(bs)) {
    const cur = as[name];
    if (!cur) add(true, `secrets.${name}`, `secret "${name}" was removed — callers that pass it will fail`);
    else if (!old.required && cur.required) add(true, `secrets.${name}`, `secret "${name}" is now required`);
    else if (old.required && !cur.required) add(false, `secrets.${name}`, `secret "${name}" is now optional`);
  }
  for (const [name, cur] of Object.entries(as)) {
    if (!bs[name])
      add(
        cur.required && wasCallable,
        `secrets.${name}`,
        `secret "${name}" was added${cur.required ? ' as required' : ''}`,
      );
  }

  for (const [name, old] of Object.entries(bi.outputs)) {
    const cur = ai.outputs[name];
    if (!cur)
      add(true, `outputs.${name}`, `output "${name}" was removed — consumers reading it get an empty value`);
    else if (!same(old, cur)) add(false, `outputs.${name}`, `output "${name}" changed`);
  }
  for (const name of Object.keys(ai.outputs)) {
    if (!bi.outputs[name]) add(false, `outputs.${name}`, `output "${name}" was added`);
  }

  if (before.path !== after.path) {
    add(
      wasCallable,
      'path',
      `path changed from ${before.path} to ${after.path}${wasCallable ? ' — callers referencing the old path will fail' : ''}`,
    );
  }
  if (!same(before.triggers, after.triggers)) {
    const lost = (before.triggers ?? []).filter((t) => !(after.triggers ?? []).includes(t));
    add(
      lost.includes('workflow_call'),
      'triggers',
      `triggers changed from [${(before.triggers ?? []).join(', ')}] to [${(after.triggers ?? []).join(', ')}]`,
    );
  }
  if (before.name !== after.name)
    add(false, 'name', `name changed from "${before.name ?? ''}" to "${after.name ?? ''}"`);

  const byJob = (calls: Contract['calls']) => new Map((calls ?? []).map((c) => [c.job, c]));
  const bc = byJob(before.calls);
  const ac = byJob(after.calls);
  for (const [job, old] of bc) {
    const cur = ac.get(job);
    if (!cur) add(false, `calls.${job}`, `jobs.${job} no longer calls ${old.uses}`);
    else if (!same(old, cur)) {
      const details: string[] = [];
      if (old.uses !== cur.uses) details.push(`now calls ${cur.uses}`);
      for (const k of new Set([...Object.keys(old.with ?? {}), ...Object.keys(cur.with ?? {})])) {
        const o = old.with?.[k];
        const n = cur.with?.[k];
        if (o !== n)
          details.push(
            o === undefined ? `passes ${k}` : n === undefined ? `stopped passing ${k}` : `changed ${k}`,
          );
      }
      if (!same(old.secrets, cur.secrets)) details.push('secrets changed');
      if (!same(old.matrix, cur.matrix)) details.push('matrix changed');
      if (!same(old.needs, cur.needs)) details.push('needs changed');
      add(false, `calls.${job}`, `jobs.${job}: ${details.join(', ') || 'call changed'}`);
    }
  }
  for (const [job, cur] of ac)
    if (!bc.has(job)) add(false, `calls.${job}`, `jobs.${job} now calls ${cur.uses}`);

  if (!same(before.uses, after.uses)) add(false, 'uses', 'local action usage changed');
  if (!same(before.consumers, after.consumers)) {
    const key = (c: Contract['consumers'][number]) => `${c.from}#${c.job ?? ''}#${c.step ?? ''}`;
    const bk = new Set(before.consumers.map(key));
    const ak = new Set(after.consumers.map(key));
    const added = [...ak].filter((k) => !bk.has(k)).length;
    const removed = [...bk].filter((k) => !ak.has(k)).length;
    add(
      false,
      'consumers',
      added || removed
        ? `consumers changed (+${added} / -${removed})`
        : 'what consumers pass or read changed',
    );
  }
  return changes;
}

// ---------------------------------------------------------------------------
// Reading existing contracts and planning updates
// ---------------------------------------------------------------------------

export interface ExistingContract {
  file: string;
  text: string;
  contract?: Contract;
  error?: string;
}

/** Every contract file. */
export function readContracts(fs: FileSystem): Map<string, ExistingContract> {
  const out = new Map<string, ExistingContract>();
  for (const file of fs
    .walk(CONTRACTS_DIR)
    .filter((f) => f.endsWith('.contract.yml'))
    .sort()) {
    const text = fs.read(file) ?? '';
    try {
      const parsed = contractSchema.safeParse(parseYaml(text));
      out.set(
        file,
        parsed.success
          ? { file, text, contract: parsed.data }
          : {
              file,
              text,
              error: parsed.error.issues
                .map((i) => `${i.path.join('.') || '(root)'}: ${i.message}`)
                .join('; '),
            },
      );
    } catch (err) {
      out.set(file, { file, text, error: `not valid YAML: ${(err as Error).message.split('\n')[0]}` });
    }
  }
  return out;
}

export type ContractStatus = 'create' | 'update' | 'delete' | 'unchanged';

export interface ContractPlanEntry {
  file: string;
  status: ContractStatus;
  /** The workflow/action this contract describes (absent for orphaned contracts). */
  unit?: string;
  before?: string;
  after?: string;
  changes: ContractChange[];
  /** Set when the existing file could not be read as a contract. */
  invalid?: string;
  /** Set when the unit could not be analyzed (e.g. YAML syntax errors) and its locked contract was kept. */
  skipped?: string;
}

export interface ContractPlan {
  entries: ContractPlanEntry[];
  /** Units whose contract was not regenerated because the file has YAML syntax errors. */
  skipped: string[];
  /** True when any file would be created, updated or deleted. */
  drift: boolean;
  counts: Record<ContractStatus, number>;
  breaking: number;
}

/** Compares the contracts on disk with the ones the current workflows produce. */
export function planContracts(index: ProjectIndex, fs: FileSystem): ContractPlan {
  const dir = CONTRACTS_DIR;
  const existing = readContracts(fs);
  const entries: ContractPlanEntry[] = [];
  const units = index.units().sort((a, b) => byCodePoint(a.path, b.path));
  // A contract that names a unit is matched by path even if it was written under another file name, so adding
  // `ci.yaml` next to `ci.yml` does not move `ci.yml`'s contract (and diff it against the wrong workflow).
  const lockedFile = new Map<string, string>();
  for (const [file, prev] of existing) {
    const c = prev.contract;
    if (c && !lockedFile.has(c.path) && units.some((u) => u.path === c.path && u.kind === c.kind))
      lockedFile.set(c.path, file);
  }
  const expected = new Map<string, UnitDecl>();
  const taken = new Set(lockedFile.values());
  for (const unit of units) {
    const file = lockedFile.get(unit.path) ?? contractFileFor(unit, taken, dir);
    taken.add(file);
    expected.set(file, unit);
  }
  const skipped: string[] = [];
  // A caller that does not parse cannot say what it passes; keep its consumer entries from the locked contracts.
  const broken = new Set(units.filter((u) => u.parseErrors.length > 0).map((u) => u.path));
  for (const [file, unit] of expected) {
    const prev = existing.get(file);
    // A contract derived from a file that is not valid YAML would erase its interface: keep the locked one.
    if (unit.parseErrors.length > 0) {
      skipped.push(unit.path);
      if (prev) {
        entries.push({
          file,
          status: 'unchanged',
          unit: unit.path,
          before: prev.text,
          after: prev.text,
          changes: [],
          skipped: 'YAML syntax errors',
        });
      }
      continue;
    }
    const contract = buildContract(index, unit);
    if (broken.size && prev?.contract) {
      contract.consumers = [
        ...contract.consumers.filter((c) => !broken.has(c.from)),
        ...prev.contract.consumers.filter((c) => broken.has(c.from)),
      ].sort((a, b) =>
        byCodePoint(`${a.from}#${a.job ?? ''}#${a.step ?? ''}`, `${b.from}#${b.job ?? ''}#${b.step ?? ''}`),
      );
    }
    const after = serializeContract(contract);
    if (!prev) {
      entries.push({ file, status: 'create', unit: unit.path, after, changes: [] });
      continue;
    }
    // Checkouts with core.autocrlf convert line endings; the content is what matters.
    if (normalizeContractText(prev.text) === after) {
      entries.push({ file, status: 'unchanged', unit: unit.path, before: prev.text, after, changes: [] });
      continue;
    }
    entries.push({
      file,
      status: 'update',
      unit: unit.path,
      before: prev.text,
      after,
      changes: prev.contract ? diffContracts(prev.contract, contract) : [],
      ...(prev.error ? { invalid: prev.error } : {}),
    });
  }
  for (const [file, prev] of existing) {
    if (expected.has(file)) continue;
    entries.push({
      file,
      status: 'delete',
      ...(prev.contract ? { unit: prev.contract.path } : {}),
      before: prev.text,
      changes: [],
      ...(prev.error ? { invalid: prev.error } : {}),
    });
  }
  entries.sort((a, b) => byCodePoint(a.file, b.file));
  const counts: Record<ContractStatus, number> = { create: 0, update: 0, delete: 0, unchanged: 0 };
  for (const e of entries) counts[e.status]++;
  return {
    entries,
    skipped,
    drift: entries.some((e) => e.status !== 'unchanged'),
    counts,
    breaking: entries.reduce((n, e) => n + e.changes.filter((c) => c.breaking).length, 0),
  };
}

/** A unified diff of the plan, with git headers, applicable with `git apply` from the repository root. */
export function contractPatch(plan: ContractPlan): string {
  const parts: string[] = [];
  for (const e of plan.entries) {
    if (e.status === 'unchanged') continue;
    const before = e.status === 'create' ? '' : (e.before ?? '');
    const after = e.status === 'delete' ? '' : (e.after ?? '');
    const patch = structuredPatch(`a/${e.file}`, `b/${e.file}`, before, after, '', '', { context: 3 });
    const body = formatPatch(patch)
      .split('\n')
      .filter((_l, i, all) => i > all.findIndex((x) => x.startsWith('+++')))
      .join('\n');
    const header = [`diff --git a/${e.file} b/${e.file}`];
    if (e.status === 'create') header.push('new file mode 100644', '--- /dev/null', `+++ b/${e.file}`);
    else if (e.status === 'delete')
      header.push('deleted file mode 100644', `--- a/${e.file}`, '+++ /dev/null');
    else header.push(`--- a/${e.file}`, `+++ b/${e.file}`);
    parts.push(`${header.join('\n')}\n${body.replace(/\n*$/, '\n')}`);
  }
  return parts.join('');
}

/** A contract path that flowpact refuses to write (a symlink, or outside the repository). */
export class UnsafePathError extends Error {}

function isSymlink(abs: string): boolean {
  try {
    return lstatSync(abs).isSymbolicLink();
  } catch {
    return false;
  }
}

/**
 * The real path of `p`: its nearest existing ancestor resolved, with the rest appended. `native` gives the canonical
 * letter case on case-insensitive file systems (macOS), so another spelling of the same directory compares equal.
 */
function realpathNearest(p: string): string {
  const rest: string[] = [];
  let at = resolve(p);
  for (;;) {
    try {
      return join(realpathSync.native(at), ...rest.reverse());
    } catch {
      const parent = dirname(at);
      if (parent === at) return resolve(p);
      rest.push(basename(at));
      at = parent;
    }
  }
}

const withinOrAt = (root: string, p: string) => {
  const rel = relative(root, p);
  return rel === '' || (rel !== '..' && !rel.startsWith(`..${sep}`) && !isAbsolute(rel));
};

/**
 * Whether `p` is `tree` or inside it, decided from canonical real paths (symlinks resolved, the file system's letter
 * case), also for paths that do not exist yet. Unlike `insideRepository`, nothing (such as `.git`) is left out: use it
 * where "inside" is the cautious answer, such as deciding that a file came with the checkout.
 */
export function pathInside(tree: string, p: string): boolean {
  return withinOrAt(realpathNearest(tree), realpathNearest(p));
}

/**
 * Refuses to write a file (a report, a patch, a contract) at a path that leads into one of `trees` (the repository, the
 * CI workspace) and then through a symlink: one that is the file itself, or that leads out of the tree again. A pull
 * request can commit those. Whether a path leads into a tree is decided from the real path of each of its ancestors, so
 * no other spelling of it (`/tmp` for `/private/tmp`, a symlink outside pointing in) skips the check. Paths that never
 * enter a tree, such as `$GITHUB_STEP_SUMMARY`, are written as given.
 */
export function assertSafeWritePath(abs: string, trees: string[]): void {
  const target = resolve(abs);
  const realParent = realpathNearest(dirname(target));
  const ancestors: string[] = [];
  for (let at = target; ; at = dirname(at)) {
    ancestors.push(at);
    if (dirname(at) === at) break;
  }
  for (const tree of trees) {
    const realTree = realpathNearest(tree);
    const enters = ancestors.some((a) => existsSync(a) && withinOrAt(realTree, realpathSync.native(a)));
    if (!enters && !withinOrAt(resolve(tree), target)) continue;
    if (isSymlink(target) || !withinOrAt(realTree, realParent))
      throw new UnsafePathError(`Not writing ${abs}: it is a symlink, or links outside ${tree}`);
  }
}

/**
 * Applies a plan to disk. With `outDir`, files are written there (same relative paths) instead of the repository,
 * and deletions are skipped — used to hand regenerated contracts to people who cannot run flowpact. `trees` are where
 * such a write must not go through a symlink (default: the repository).
 */
export function writeContracts(
  root: string,
  plan: ContractPlan,
  outDir?: string,
  trees: string[] = [root],
): string[] {
  const written: string[] = [];
  const base = outDir ?? root;
  // An output directory inside the repository is checked like a report path, every file before any is written.
  if (outDir)
    for (const e of plan.entries) if (e.status !== 'delete') assertSafeWritePath(join(outDir, e.file), trees);
  // Contracts are written into the checkout; a symlink there must not redirect a write (or delete) elsewhere. Every
  // target is checked before anything is written, so a refusal leaves the directory as it was.
  if (!outDir) {
    const unsafe = plan.entries
      .filter((e) => e.status !== 'unchanged')
      .map((e) => e.file)
      .filter((f) => isSymlink(join(root, f)) || !insideRepository(root, join(root, f)));
    if (unsafe.length)
      throw new UnsafePathError(
        `Not writing contracts: ${unsafe.join(', ')} ${unsafe.length === 1 ? 'is a symlink or links' : 'are symlinks or link'} outside the repository`,
      );
  }
  for (const e of plan.entries) {
    const abs = join(base, e.file);
    if (e.status === 'delete') {
      if (!outDir && existsSync(abs)) {
        rmSync(abs);
        written.push(e.file);
      }
      continue;
    }
    if (e.status === 'unchanged' && !outDir) continue;
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, e.after ?? '');
    written.push(e.file);
  }
  return written;
}

/** Units listed as consumers in the locked or regenerated contract of an entry (callers and action users). */
export function entryConsumers(e: ContractPlanEntry): string[] {
  const out = new Set<string>();
  for (const text of [e.before, e.after]) {
    if (!text) continue;
    try {
      const data = parseYaml(text) as { consumers?: { from?: unknown }[] } | null;
      for (const c of data?.consumers ?? []) if (typeof c?.from === 'string') out.add(c.from);
    } catch {
      // An unreadable contract has no usable consumers list.
    }
  }
  return [...out];
}

/**
 * With paths (`flowpact check <paths>`, `flowpact generate <paths>`): the contracts of the targeted workflows and
 * actions, and the contracts they appear in as a consumer, since what a caller passes or reads is locked in its
 * callee's contract.
 */
export function contractsInScope(index: ProjectIndex): (e: ContractPlanEntry) => boolean {
  const { targets } = index.project;
  const targeted = (unit: string) => targets.has(index.unit(unit)?.file ?? unit);
  return (e) => (e.unit !== undefined && targeted(e.unit)) || entryConsumers(e).some(targeted);
}

/** The part of a plan that concerns `keep`: drift, counts and the patch then only cover those units. */
export function scopePlan(plan: ContractPlan, keep: (e: ContractPlanEntry) => boolean): ContractPlan {
  const entries = plan.entries.filter(keep);
  const counts: Record<ContractStatus, number> = { create: 0, update: 0, delete: 0, unchanged: 0 };
  for (const e of entries) counts[e.status]++;
  return {
    entries,
    skipped: plan.skipped.filter((u) => entries.some((e) => e.unit === u)),
    drift: entries.some((e) => e.status !== 'unchanged'),
    counts,
    breaking: entries.reduce((n, e) => n + e.changes.filter((c) => c.breaking).length, 0),
  };
}
