import {
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { CONFIG_DIR, CONFIG_FILES, LEGACY_CONFIG_DIR, LEGACY_CONFIG_FILES } from './config';
import { CONTRACT_HEADER, CONTRACTS_DIR } from './contracts';
import { insideRepository } from './project';

/** One file moved from wfc's pre-0.2.0 location to flowpact's, with its content rewritten. */
export interface MigrationMove {
  from: string;
  to: string;
  /** What changed in the content (empty when the file is only moved). */
  changes: string[];
}

export interface MigrationPlan {
  moves: MigrationMove[];
  /** Destinations that already exist; nothing is migrated while there are conflicts. */
  conflicts: string[];
  /** Files in the old directory that flowpact does not know; they are left in place. */
  leftovers: string[];
}

const toPosix = (p: string) => p.split('\\').join('/');
const OLD_SCHEMA_BASE = 'https://rumankazi.github.io/wfc/';
const NEW_SCHEMA_BASE = 'https://rumankazi.github.io/flowpact/';
const OLD_HEADER =
  /^# Generated by wfc — do not edit by hand\. Run `wfc generate` to update\.\n# Docs: https:\/\/rumankazi\.github\.io\/wfc\/docs\/contracts\n/;

function walk(root: string, dir: string): string[] {
  const abs = join(root, dir);
  if (!existsSync(abs)) return [];
  const out: string[] = [];
  for (const name of readdirSync(abs).sort()) {
    const rel = toPosix(join(dir, name));
    const st = lstatSync(join(root, rel));
    if (st.isSymbolicLink()) continue;
    if (st.isDirectory()) out.push(...walk(root, rel));
    else out.push(rel);
  }
  return out;
}

/** The rewritten config: `WFC` rule codes become `FP`, schema URLs point at flowpact. */
export function migrateConfigText(text: string): { text: string; changes: string[] } {
  const changes: string[] = [];
  let out = text.replace(/\bWFC(\d{3})\b/g, (_, n: string) => {
    changes.push(`WFC${n} → FP${n}`);
    return `FP${n}`;
  });
  if (out.includes(OLD_SCHEMA_BASE)) {
    out = out.split(OLD_SCHEMA_BASE).join(NEW_SCHEMA_BASE);
    changes.push('schema URL');
  }
  return { text: out, changes: [...new Set(changes)] };
}

/** The rewritten contract: flowpact header and schema URL, so `flowpact check` sees it as up to date. */
export function migrateContractText(text: string): { text: string; changes: string[] } {
  const changes: string[] = [];
  let out = text;
  if (OLD_HEADER.test(out)) {
    out = out.replace(OLD_HEADER, CONTRACT_HEADER);
    changes.push('header');
  }
  if (out.includes(OLD_SCHEMA_BASE)) {
    out = out.split(OLD_SCHEMA_BASE).join(NEW_SCHEMA_BASE);
    changes.push('schema URL');
  }
  return { text: out, changes };
}

/** What `flowpact migrate` would do in `root`. */
export function planMigration(root: string): MigrationPlan {
  const moves: MigrationMove[] = [];
  const leftovers: string[] = [];
  for (const file of walk(root, LEGACY_CONFIG_DIR)) {
    const name = file.slice(LEGACY_CONFIG_DIR.length + 1);
    const configIndex = (LEGACY_CONFIG_FILES as readonly string[]).indexOf(name);
    const text = readFileSync(join(root, file), 'utf8');
    if (configIndex >= 0) {
      const { changes } = migrateConfigText(text);
      moves.push({ from: file, to: `${CONFIG_DIR}/${CONFIG_FILES[configIndex]}`, changes });
    } else if (/^(workflows|actions)\/.+\.contract\.yml$/.test(name)) {
      const { changes } = migrateContractText(text);
      moves.push({ from: file, to: `${CONTRACTS_DIR}/${name}`, changes });
    } else {
      leftovers.push(file);
    }
  }
  const conflicts = moves.map((m) => m.to).filter((to) => existsSync(join(root, to)));
  return { moves, conflicts, leftovers };
}

/** Moves the files of a plan without conflicts and removes the old directory when it is empty. */
export function applyMigration(root: string, plan: MigrationPlan): void {
  if (plan.conflicts.length) throw new Error(`Already exists: ${plan.conflicts.join(', ')}`);
  for (const m of plan.moves) {
    const from = join(root, m.from);
    const to = join(root, m.to);
    if (!insideRepository(root, from) || !insideRepository(root, to)) {
      throw new Error(`${m.from} → ${m.to} leaves the repository`);
    }
    const text = readFileSync(from, 'utf8');
    const migrated = m.to.endsWith('.contract.yml') ? migrateContractText(text) : migrateConfigText(text);
    mkdirSync(dirname(to), { recursive: true });
    writeFileSync(to, migrated.text);
    rmSync(from);
  }
  // Remove directories the move emptied, deepest first; anything left behind (leftovers) keeps its directory.
  const dirs = [...new Set(plan.moves.map((m) => dirname(join(root, m.from))))].sort(
    (a, b) => b.length - a.length,
  );
  for (const d of [...dirs, join(root, LEGACY_CONFIG_DIR)]) {
    if (
      existsSync(d) &&
      readdirSync(d).length === 0 &&
      toPosix(relative(root, d)).startsWith(LEGACY_CONFIG_DIR)
    ) {
      rmdirSync(d);
    }
  }
}
