/**
 * Generates one MDX page per rule (plus an index) from the rule registry, so the docs, `wfc explain`
 * and the docs URLs printed with every finding can never drift apart.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CATEGORIES, createRegistry, type RuleDefinition } from '@wfc/core';

const OUT = join(import.meta.dirname, '../apps/docs/content/docs/rules');

const SEVERITY_BADGE: Record<string, string> = {
  error: '🔴 error',
  warning: '🟡 warning',
  info: '🔵 info',
  off: '⚪ off (opt-in)',
};

/** Escapes text for MDX prose (braces and angle brackets would be parsed as JSX). */
const mdx = (s: string) => s.replace(/[{}<>]/g, (c) => `\\${c}`);

export function rulePage(rule: RuleDefinition): string {
  const category = Object.values(CATEGORIES).find((c) => c.id === rule.category)!;
  const lines = [
    '---',
    `title: '${rule.code} · ${rule.name}'`,
    `description: ${JSON.stringify(rule.docs.summary)}`,
    '---',
    '',
    `{/* Generated by scripts/gen-rule-docs.ts from packages/core/src/rules — edit the rule, not this file. */}`,
    '',
    '| Code | Name | Category | Default severity |',
    '| --- | --- | --- | --- |',
    `| \`${rule.code}\` | \`${rule.name}\` | ${category.title} | ${SEVERITY_BADGE[rule.defaultSeverity]} |`,
    '',
    '## Why it matters',
    '',
    mdx(rule.docs.why),
    '',
    '## How to fix',
    '',
    mdx(rule.docs.fix),
    '',
  ];
  if (rule.docs.examples) {
    lines.push(
      '## Example',
      '',
      '<Tabs items={["Problem", "Fixed"]}>',
      '<Tab value="Problem">',
      '',
      '```yaml',
      rule.docs.examples.bad,
      '```',
      '',
      '</Tab>',
      '<Tab value="Fixed">',
      '',
      '```yaml',
      rule.docs.examples.good,
      '```',
      '',
      '</Tab>',
      '</Tabs>',
      '',
    );
  }
  lines.push(
    '## Configure',
    '',
    'Change the severity (or turn the rule off) in `.github/workflow-contracts/wfc.config.yml`, by code or by name:',
    '',
    '```yaml title=".github/workflow-contracts/wfc.config.yml"',
    'rules:',
    `  ${rule.code}: ${rule.defaultSeverity === 'off' ? 'warning' : 'off'}`,
    `  # or: ${rule.name}: error`,
    '```',
    '',
    'Explain it in the terminal:',
    '',
    '```sh',
    `wfc explain ${rule.code}`,
    '```',
    '',
  );
  return lines.join('\n');
}

export function indexPage(rules: RuleDefinition[]): string {
  const lines = [
    '---',
    'title: Rules',
    'description: Every finding wfc reports, grouped by category. Each code links to why it matters and how to fix it.',
    '---',
    '',
    '{/* Generated by scripts/gen-rule-docs.ts — edit the rules, not this file. */}',
    '',
    'Codes have the form `<PREFIX><category><nn>` — built-in rules use `WFC`, so `WFC4xx` are matrix rules.',
    'Severity is configurable per rule; codes never change meaning. Plugin rules use their own prefix (for example `ACME101`).',
    '',
  ];
  for (const [digit, cat] of Object.entries(CATEGORIES)) {
    const inCat = rules.filter((r) => r.category === cat.id);
    if (inCat.length === 0) continue;
    lines.push(
      `## ${cat.title} (\`WFC${digit}xx\`)`,
      '',
      '| Code | Name | Default | Summary |',
      '| --- | --- | --- | --- |',
    );
    for (const r of inCat) {
      lines.push(
        `| [\`${r.code}\`](/docs/rules/${r.code.toLowerCase()}) | \`${r.name}\` | ${SEVERITY_BADGE[r.defaultSeverity]} | ${mdx(r.docs.summary).replace(/\|/g, '\\|')} |`,
      );
    }
    lines.push('');
  }
  lines.push(
    '## Reserved ranges',
    '',
    '- `WFC7xx` — hygiene rules (reserved).',
    '- `WFC8xx` — contract drift (`contract-missing`, `contract-stale`, `breaking-interface-change`), shipping with `wfc check`.',
    '- `WFC9xx` — config and overrides (`override-expired`, `override-unused`, `invalid-config`), shipping with overrides.',
    '',
  );
  return lines.join('\n');
}

if (import.meta.main ?? process.argv[1]?.endsWith('gen-rule-docs.ts')) {
  const rules = createRegistry().all();
  mkdirSync(OUT, { recursive: true });
  for (const f of readdirSync(OUT)) if (/^wfc\d{3}\.mdx$/.test(f)) rmSync(join(OUT, f));
  for (const rule of rules) writeFileSync(join(OUT, `${rule.code.toLowerCase()}.mdx`), rulePage(rule));
  writeFileSync(join(OUT, 'index.mdx'), indexPage(rules));
  writeFileSync(
    join(OUT, 'meta.json'),
    `${JSON.stringify({ title: 'Rules', pages: ['index', ...rules.map((r) => r.code.toLowerCase())] }, null, 2)}\n`,
  );
  console.log(`wrote ${rules.length} rule pages to ${OUT}`);
}
